default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: ""
  password: ""

development:
  <<: *default

staging:
  <<: *default
  database: acra_staging

test:
  <<: *default
  database: acra_test

production:
  <<: *default
  database: acra_prod
